### ISSUE TITLE
pink material

### ISSUE THREAD

**Issue by eloimaduell** [Avdbergnmf/UnityURPMirrorShader#1]
I just donwloaded the ZIP and add it to my scene which is a URP in Unity 2020.1.b08.
The material Flowing Water Ripples looks pink. Am I doing something  wrong ? Wrong version ? Maybe something wrong on my URP Render settings? 

Here is my console at load ...

```
ScriptedImporter for asset: Assets/Materials/WaterWithFlowmap.shadergraph, reported an invalid import dependency: 00000000000000000000000000000000

ScriptedImporter for asset: Assets/UnityURPMirrorShader-master/WaterWithFlowmap.shadergraph, reported an invalid import dependency: 00000000000000000000000000000000

Error in Graph at Assets/Materials/WaterWithFlowmap.shadergraph at node Intersections: Could not find Sub Graph asset with GUID ff1668980e74fda4d95abfd5d1302c09.
UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext) (at /Users/builduser/buildslave/unity/build/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)

Error in Graph at Assets/UnityURPMirrorShader-master/WaterWithFlowmap.shadergraph at node TextureScroll: Could not find Sub Graph asset with GUID 4c79605289830f44cbc40fb8c38e1fe0.
UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext) (at /Users/builduser/buildslave/unity/build/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)

Error in Graph at Assets/UnityURPMirrorShader-master/WaterWithFlowmap.shadergraph at node Intersections: Could not find Sub Graph asset with GUID ff1668980e74fda4d95abfd5d1302c09.
UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext) (at /Users/builduser/buildslave/unity/build/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)

Unity is only able to load mdb or portable-pdb symbols. Packages/com.unity.ext.nunit/net35/unity-custom/nunit.framework.pdb is using a legacy pdb format.
UnityEngine.Debug:LogWarning(Object)
Microsoft.Unity.VisualStudio.Editor.VisualStudioEditor:SyncIfNeeded(String[], String[], String[], String[], String[]) (at Library/PackageCache/com.unity.ide.visualstudio@2.0.1/Editor/VisualStudioEditor.cs:146)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[]) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:172)



```

**Comment by eloimaduell** [comment]
I started from scratch a new URP project and I couldn't reproduce the same error from my previous post. So I'm not sure how I ended there, but now I'm facing still a pink material problem.

If I use the option "Edit->Render Pipeline->URP->Upgrade Selected Materials" with a new scene inside a URP project (which I've included the folder of this repo), I get this error on the console : 

FlowingWaterRipples material was not upgraded. There's no upgrader to convert Shader Graphs/WaterWithFlowmap shader to selected pipeline
UnityEditor.Rendering.Universal.UniversalRenderPipelineMaterialUpgrader:UpgradeSelectedMaterials() (at Library/PackageCache/com.unity.render-pipelines.universal@7.3.1/Editor/UniversalRenderPipelineMaterialUpgrader.cs:37)

This error is arised by Mirror.cs 396 and the selected material was FlowingWaterRipples from  this repo.

**Comment by JordiXaloc** [comment]
Hi,
I have the same problem. The custom nodes aren´t included in the github
![imagen](https://user-images.githubusercontent.com/66940157/102076543-24068680-3e08-11eb-91a8-a5a2f15c691b.png)

**Comment by Avdbergnmf** [comment]
oof, that's stupid on my part. I will try to reupload somewhere this week! Will take me some figuring out so please be patient

**Comment by klaszlo8207** [comment]
any news on this? I got pink materials too

**Comment by kevincastejon** [comment]
same here

**Comment by Avdbergnmf** [comment]
Made a new commit with the subgraphs included. Could you all give it another go and see if it renders correctly now?

Sorry for the delay, got buisy doing actual work ;)

**Comment by Avdbergnmf** [comment]
If someone can confirm for me if everything works, I'll close this issue!

**Comment by kevincastejon** [comment]
i'll try ASAP

**Comment by Avdbergnmf** [comment]
And?
